name: publish

on: [push]

jobs:
  publish-qbitmf-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the qbitmf Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u twist3dimages --password-stdin
      env:
        CR_PAT: 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
